# Generated by Django 4.2.30 on 2026-08-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_times_answered_question_times_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile'), ('expert', 'Expert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.TextField(),
        ),
    ]
