# Generated by Django 4.2.30 on 2026-07-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('badge_type', models.CharField(choices=[('milestone', 'Étape'), ('streak', 'Régularité'), ('difficulty', 'Difficulté'), ('speed', 'Vitesse'), ('accuracy', 'Précision'), ('special', 'Spécial')], max_length=20)),
                ('condition_key', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('avatar', 'Avatar'), ('photo', 'Photo')], default='avatar', max_length=10)),
                ('avatar', models.CharField(choices=[('lion', 'Lion'), ('colombe', 'Colombe'), ('agneau', 'Agneau'), ('etoile', 'Étoile'), ('feu', 'Feu'), ('couronne', 'Couronne'), ('livre', 'Livre'), ('croix', 'Croix'), ('arc', 'Arc-en-ciel'), ('ancre', 'Ancre'), ('epee', 'Épée'), ('lumiere', 'Lumière')], default='lion', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Photo personnelle (optionnel)', null=True, upload_to='photos_profil/')),
                ('total_xp', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_played', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
