# Generated by Django 4.2.30 on 2026-07-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=game.models.generate_code, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('time_per_question', models.IntegerField(default=15, help_text='Secondes — anti-IA')),
                ('question_count', models.IntegerField(default=10)),
                ('book_filter', models.CharField(blank=True, max_length=100)),
                ('difficulty_filter', models.CharField(default='all', max_length=20)),
                ('questions_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('is_ready', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('game', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(blank=True, max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.FloatField(default=0, help_text='Secondes pour répondre')),
                ('points', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gameplayer')),
            ],
            options={
                'unique_together': {('player', 'question_id')},
            },
        ),
    ]
