# Generated by Django 4.2.30 on 2026-10-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_current_question_index_game_question_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('finished', 'Terminé'), ('expired', 'Expiré')], default='waiting', max_length=20),
        ),
    ]
